-- Rolling 24-hour quota for Kenji AI. The Edge Function calls these helpers
-- with the verified auth user id; clients never choose whose quota is changed.
create table if not exists public.ai_question_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  asked_at timestamptz not null default now()
);

create index if not exists ai_question_usage_user_asked_idx
  on public.ai_question_usage (user_id, asked_at desc);

alter table public.ai_question_usage enable row level security;

revoke all on table public.ai_question_usage from anon, authenticated;

create or replace function public.get_ai_question_quota(
  p_user_id uuid,
  p_limit integer default 5
)
returns table (
  allowed boolean,
  used integer,
  remaining integer,
  reset_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_used integer;
  v_oldest timestamptz;
begin
  if p_user_id is null or p_limit < 1 then
    raise exception 'invalid quota arguments';
  end if;

  select count(*)::integer, min(asked_at)
    into v_used, v_oldest
  from public.ai_question_usage
  where user_id = p_user_id
    and asked_at > v_now - interval '24 hours';

  return query select
    v_used < p_limit,
    v_used,
    greatest(p_limit - v_used, 0),
    case when v_oldest is null then null else v_oldest + interval '24 hours' end;
end;
$$;

create or replace function public.consume_ai_question(
  p_user_id uuid,
  p_limit integer default 5
)
returns table (
  allowed boolean,
  used integer,
  remaining integer,
  reset_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_used integer;
  v_oldest timestamptz;
begin
  if p_user_id is null or p_limit < 1 then
    raise exception 'invalid quota arguments';
  end if;

  -- Serialize requests for one user so parallel calls cannot exceed the limit.
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  select count(*)::integer, min(asked_at)
    into v_used, v_oldest
  from public.ai_question_usage
  where user_id = p_user_id
    and asked_at > v_now - interval '24 hours';

  if v_used >= p_limit then
    return query select false, v_used, 0, v_oldest + interval '24 hours';
    return;
  end if;

  insert into public.ai_question_usage (user_id, asked_at)
  values (p_user_id, v_now);

  v_used := v_used + 1;
  if v_oldest is null then v_oldest := v_now; end if;

  return query select true, v_used, greatest(p_limit - v_used, 0), v_oldest + interval '24 hours';
end;
$$;

revoke all on function public.get_ai_question_quota(uuid, integer) from public, anon, authenticated;
revoke all on function public.consume_ai_question(uuid, integer) from public, anon, authenticated;
grant execute on function public.get_ai_question_quota(uuid, integer) to service_role;
grant execute on function public.consume_ai_question(uuid, integer) to service_role;

